export const SET_INDEX_PAGE_LIST = 'SET_INDEX_PAGE_LIST';
export const SET_RECOMMENDED_LIST = 'SET_RECOMMENDED_LIST';
export const SET_INIT_INDEX_PAGE_LIST_PARAMS = 'SET_INIT_INDEX_PAGE_LIST_PARAMS';
